### ISSUE TITLE
source hdd won't boot after running weresync

### ISSUE THREAD

**Issue by kalakuta** [DonyorM/weresync#11]
When I tried WereSync to clone my 500GB HDD to a 250GB SSD, neither my new SSD nor my original HDD would boot at all.  So I've gone from a working system to a broken one...

Any ideas as to what to try?  My original set-up was headless, but attaching to a monitor and booting just leads to a blank screen; the various recovery options don't yield anything, but if I choose Run UEFI Application I can run grubx64.efi and successfully boot the system.  But I'm at a loss as to how to make this happen automatically (and I need to switch it back to a headless system...)

Any help gratefully received!

**Comment by kirbyfan64** [comment]
Do have Secure Boot enabled or something? You might have to re-add your EFI files and trusted in your BIOS.

**Comment by DonyorM** [comment]
I believe I had this happen with my drive, though I did manage to get to the grub commandline.

Can you boot to the SSD (using Run EFI Application) and post the output of `sudo blkid`? Then please post the contents of the grub.cfg file in the same directory as grubx64.efi?

Also, what model machine are you using? Is it an Asus, Lenovo, etc?

**Comment by kalakuta** [comment]
Machine is an HP8300 mini-tower, running xubuntu 16.04

I'll post the outputs in a couple of days' time - I'm away from home at the moment.

In the meantime, I have got the HDD back up and running, by booting the machine using grubx64.efi, and then using `sudo grub-install /dev/sda`.  I haven't yet tried this with the SDD, but am hoping this might fix things too.

**Comment by DonyorM** [comment]
I'm going to close this since the issue seems to be solved. Feel free to reopen it if you need further help.
