### ISSUE TITLE
Cannot target /dev/nvme0n1 but /dev/sd? seems to work fine.

### ISSUE THREAD

**Issue by ColeRominger** [DonyorM/weresync#16]
$ sudo weresync -v /dev/sdb /dev/nvme0n1 -g2 -B1 -E1
Beginning to copy files.
WARNING - 2018-10-31 10:42:20,846 - weresync.device - Error copying data for partition 1 from device /dev/sdb to /dev/nvme0n1.
WARNING - 2018-10-31 10:42:20,853 - weresync.device - Error copying data for partition 2 from device /dev/sdb to /dev/nvme0n1.
Finished copying files.
Finished copying files.
Making bootable
INFO - 2018-10-31 10:42:20,853 - weresync.device - Using plugin: uuid_copy
WARNING - 2018-10-31 10:42:20,892 - weresync.device - Error copying fstab. Continuing anyway.
WARNING - 2018-10-31 10:42:20,897 - weresync.device - Error copying bootloader.
All done, enjoy your drive!

Does it matter that nvme0n1 uses p1 and p2 as drive identifiers and not 1 or 2?
Like /dev/nvme0n1p1 instead of say /dev/sd?1

**Comment by DonyorM** [comment]
Yeah you found exactly why it wasn't working. You can use the part mask options to fix this. The above command should work if you add `-t {0}p{1}` to the command, thereby changing the way weresync discovers partitions for the target drive. So:
```
$ sudo weresync -v /dev/sdb /dev/nvme0n1 -g2 -B1 -E1 -t {0}p{1}
```

Sorry it took me so long to answer.

**Comment by DonyorM** [comment]
Closing this issue since I believe it is solved. Feel free to reopen if it isn't.
