### ISSUE TITLE
Installation with pip not working

### ISSUE THREAD

**Issue by DavidPortilloPrat** [DonyorM/weresync#17]
Tryng to install with pip python 3.6.7 in ubuntu 18.10 get this error
Downloading https://files.pythonhosted.org/packages/ef/f7/62352a45b181fa28c0dc6a92dc070be82c1353ae64a6092e23f200e4398d/WereSync-1.0.9.tar.gz (157kB)
    100% |████████████████████████████████| 163kB 3.0MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-HScKSK/weresync/setup.py", line 66, in <module>
        "weresync.resources": ["*.svg", "*.png"] + create_mo_files()
      File "/tmp/pip-build-HScKSK/weresync/setup.py", line 19, in create_mo_files
        if shutil.which("msgfmt") is None:
    AttributeError: 'module' object has no attribute 'which'

**Comment by kirbyfan64** [comment]
Are you positive you're running it with Python 3.6? The error seems to imply that shutil from Python 3.2 or older is being used

**Comment by DavidPortilloPrat** [comment]
I have python 2.7 and python3... if I try to install by ./setup.py I get
Traceback (most recent call last):
  File "./setup.py", line 4, in <module>
    from setuptools import setup, find_packages
ModuleNotFoundError: No module named 'setuptools'

If I ty to install with
pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)

I get

Collecting weresync
  Using cached https://files.pythonhosted.org/packages/ef/f7/62352a45b181fa28c0dc6a92dc070be82c1353ae64a6092e23f200e4398d/WereSync-1.0.9.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-lqwzqQ/weresync/setup.py", line 66, in <module>
        "weresync.resources": ["*.svg", "*.png"] + create_mo_files()
      File "/tmp/pip-build-lqwzqQ/weresync/setup.py", line 19, in create_mo_files
        if shutil.which("msgfmt") is None:
    AttributeError: 'module' object has no attribute 'which'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-lqwzqQ/weresync/

So.. I dont know what to do

**Comment by kirbyfan64** [comment]
Install python3-setuptools and python3-pip from your distro package manager (the names may vary slightly, what distro do you have?), and then do `python3 -m pip install weresync` or `python3 setup.py install`.

**Comment by DavidPortilloPrat** [comment]
I have ubuntu 18.10,,, thanks ill try... keep the good work!!

**Comment by DavidPortilloPrat** [comment]
Worked... thanks

**Comment by DonyorM** [comment]
Closing since the issue seems to be fixed. Feel free to reopen if you have any further issues.
