### ISSUE TITLE
Failed to connect to dbus service.

### ISSUE THREAD

**Issue by kwkimg3100** [DonyorM/weresync#21]
ENV
OS : Google cloud Centos7

When i used `sudo weresync -C --grub-partition 1 /dev/sda /dev/sdb`,  the command fails. 

output error
`Failed to connect to dbus service. Is it running?`

But dbus service status is active(running).

How can i solve this problem?

**Comment by jonathanhatch** [comment]
Same problem here. Anything changed?

**Comment by Raymo111** [comment]
I have the same issue. @DonyorM Can we get a fix or solution?
OS: Google Cloud Debian 10 Buster.
What I did: (Same as @kwkimg3100 I assume) https://blog.kevinlin.info/post/google-compute-engine-reducing-the-size-of-a-persistent-disk

**Comment by DonyorM** [comment]
Did you start the weresync-daemon service with `sudo weresync-daemon & >/dev/null 2>&1` before running the weresync command?

**Comment by Raymo111** [comment]
Ah no. Now it works. Thanks!

**Comment by sangaman** [comment]
I ran into this same error (trying to follow instructions from the same blog post linked above) but when I try to start the daemon service I get this error:

```
Traceback (most recent call last):
  File "/usr/local/bin/weresync-daemon", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.5/dist-packages/weresync/daemon/daemon.py", line 37, in run
    with bus.publish("net.manilas.weresync.DriveCopier", DriveCopier()):
  File "/usr/local/lib/python3.5/dist-packages/pydbus/publication.py", line 42, in publish
    return Publication(self, bus_name, *objects)
  File "/usr/local/lib/python3.5/dist-packages/pydbus/publication.py", line 35, in __init__
    self._at_exit(bus.request_name(bus_name, allow_replacement=allow_replacement, replace=replace).__exit__)
  File "/usr/local/lib/python3.5/dist-packages/pydbus/request_name.py", line 29, in request_name
    return NameOwner(self, name, allow_replacement, replace)
  File "/usr/local/lib/python3.5/dist-packages/pydbus/request_name.py", line 8, in __init__
    res = bus.dbus.RequestName(name, flags)
  File "/usr/local/lib/python3.5/dist-packages/pydbus/proxy_method.py", line 75, in __call__
    0, timeout_to_glib(timeout), None).unpack()
GLib.Error: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: Connection ":1.8" is not allowed to own the service "net.manilas.weresync.DriveCopier" due to security policies in the configuration file (9)
^C
```

Any help would be greatly appreciated.

**Comment by sangaman** [comment]
Looks like installing the .deb package instead of with pip as described here helped: https://github.com/DonyorM/weresync/issues/20#issuecomment-533905989

**Comment by DonyorM** [comment]
Yes, the .deb should handle copying the policy file properly.

**Comment by brybalicious** [comment]
Also, for anyone following 

> I have the same issue. @DonyorM Can we get a fix or solution?
> OS: Google Cloud Debian 10 Buster.
> What I did: (Same as @kwkimg3100 I assume) https://blog.kevinlin.info/post/google-compute-engine-reducing-the-size-of-a-persistent-disk

Also, for anyone following this link, the command `sudo weresync -C --grub-partition 1 /dev/sda /dev/sdb` now seems to fail. `--grub-partition` seems to have been deprecated in favor of `--root-partition` and `--boot-partition`

**Comment by SharpBCD** [comment]
For me nothing worked. Could not make weresync to work no matter what I tried. 
so I went with `$ dd if=/dev/sda of=/dev/sdb bs=1M conv=noerror,sync`
as described here:  https://askubuntu.com/questions/741723/moving-entire-linux-installation-to-another-drive

in case someone else has the same problem.
