### ISSUE TITLE
Google unable to boot after weresync completes.

### ISSUE THREAD

**Issue by jonathanhatch** [DonyorM/weresync#22]
Hey there, I'm not able to get Google VM to boot after completing the sync from a 1TB to 200GB disk. There's plenty of room (only using about 45GB), but there are some odd messages that popup when I'm completing the migration.

`Creating new GPT entries.
The operation has completed successfully.
Checking partition validity.
weresync.interface - Partition count on two drives different. Invalid.
Partitions invalid!
Copying drive partition table.
weresync.interface - Drives are incompatible.
The operation has completed successfully.
weresync.device - Invalid filesystem type found. Partition 14 not formatted.
Beginning to copy files.
weresync.device - Error copying data for partition 14 from device /dev/sda to /dev/sdb.
Copying partition 15
Copying partition 1`

**Comment by DonyorM** [comment]
Could you post the entire log file in a gist? (gist.github.com) Additionally could you post the command you used with all parameters?

**Comment by aa1121** [comment]
i'm having the same problem, VM doesn't boot with the new disk, this is my log:
any help would be appreciated, thanks in advance

asda@instance-3:~$ sudo weresync -C /dev/sda /dev/sdc
Creating new GPT entries.
The operation has completed successfully.
Checking partition validity.
WARNING - 2019-11-12 00:43:42,290 - weresync.daemon.copier - Partition count on two drives different. Invalid.
Partitions invalid!
Copying drive partition table.
WARNING - 2019-11-12 00:43:42,290 - weresync.daemon.copier - Drives are incompatible.
Checking that no-one is using this disk right now ... OK

Disk /dev/sdc: 220 GiB, 236223201280 bytes, 461373440 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
Disklabel type: dos
Disk identifier: 0xd3a8afd4

Old situation:

>>> Script header accepted.
>>> Created a new DOS disklabel with disk identifier 0xd97fc557.
/dev/sdc1: Created a new partition 1 of type 'Linux' and of size 220 GiB.
/dev/sdc2: Done.

New situation:

Device     Boot Start       End   Sectors  Size Id Type
/dev/sdc1  *     4096 461373406 461369311  220G 83 Linux

The partition table has been altered.
Calling ioctl() to re-read partition table.
Syncing disks.
Partition Table Copying: |██████████████████------------------------------------------| 30.0Partition Table Copying: |██████████████████████████████████████----------------------| 64.0Partition Table Copying: |████████████████████████████████████████████████████████████| 100.0% 
Beginning to copy files.
Copying partition 1
Copying Partition 1.0: |------------------------------------------------------------| 0.0% 
Copying Partition 1.0: |------------------------------------------------------------| 0.0% 
Copying Partition 1.0: |------------------------------------------------------------| 0.0% 


Copying Partition 1.0: |████████████████████████████████████████████████████████████| 100.0% 
Finished copying files.
Finished copying files.
Making bootable
WARNING - 2019-11-12 01:09:42,398 - weresync.daemon.device - Error copying fstab. Continuing anyway.
Bootloader installed
All done, enjoy your drive!
All done, enjoy your drive!

**Comment by aa1121** [comment]
think i figured it out, running "weresync -L grub2 -g 1 /dev/sda /dev/sdc" worked

**Comment by DonyorM** [comment]
@aa1121 Glad that worked. 

And yeah if you're not using UEFI you almost surely need to specify a bootloader (see `weresync --help`). Is there soemwhere in the documentation I can add something to make that more clear?

**Comment by aa1121** [comment]
i dont know

**Comment by jsalsman** [comment]
@LINKIWI Kevin, sorry to bother you could you please update https://blog.kevinlin.info/post/google-compute-engine-reducing-the-size-of-a-persistent-disk for installing the .deb (as per https://github.com/DonyorM/weresync/issues/20#issuecomment-533905989 ) instead of using pip; doing `$ sudo weresync-daemon > /dev/null 2>&1 &` and using that grub2 bootloader option? Your page comes up as the top google hit for shrinking GCP disks.

**Comment by yuri1992** [comment]
I read the same blog post about reducing the disk size in GCP. 
https://blog.kevinlin.info/post/google-compute-engine-reducing-the-size-of-a-persistent-disk

**Few pitfalls**
- Make sure Copy the policy file in `src/wersync/resources/weresync-dbus.conf to /etc/dbus-1/system.d. 
- Then start the daemon: Running `sudo weresync-daemon & >/dev/null 2>&1`
- `sudo weresync C -g 1 /dev/sda /dev/sdb`

**Comment by ClarinetK622** [comment]
This is an old post, but I tried to follow the solution here and had no luck. For those who are still running into problems, here is an alternative solution.

I was able to resolve my issues booting a weresync shrunken drive in GCE by **creating the new smaller drive from a public bootable image** (Ubuntu 18.04 LTS: ubuntu-1804-bionic-v20210504). This marks the the drive as UEFI compatible, whereas when I started with a blank drive it would not let me set it as a boot disk on my UEFI instance. It also created a partition 14 on the new drive by default which weresync always failed to copy over from the old one (not sure how important this is). I then mounted the drive onto my VM and cloned my source boot drive to it using weresync with the following command. Notice my source drive has an EFI partition, which also may have been the cause of my problems when following the above solutions.
 
sudo weresync -C -L grub2 -E 15 -g 1 /dev/sda /dev/sdc

I then stopped the server, replaced the large boot drive with the smaller one, and it booted right up. I had to reconfigure my fstab to get my secondary drive to mount properly, but that's it. Hopefully this helps someone stuck in my position where seemingly no solutions worked!

**Comment by kdqed** [comment]
Was stuck with the issue and this helped. Thanks @ClarinetK622 

> This is an old post, but I tried to follow the solution here and had no luck. For those who are still running into problems, here is an alternative solution.
> 
> I was able to resolve my issues booting a weresync shrunken drive in GCE by **creating the new smaller drive from a public bootable image** (Ubuntu 18.04 LTS: ubuntu-1804-bionic-v20210504). This marks the the drive as UEFI compatible, whereas when I started with a blank drive it would not let me set it as a boot disk on my UEFI instance. It also created a partition 14 on the new drive by default which weresync always failed to copy over from the old one (not sure how important this is). I then mounted the drive onto my VM and cloned my source boot drive to it using weresync with the following command. Notice my source drive has an EFI partition, which also may have been the cause of my problems when following the above solutions.
> 
> sudo weresync -C -L grub2 -E 15 -g 1 /dev/sda /dev/sdc
> 
> I then stopped the server, replaced the large boot drive with the smaller one, and it booted right up. I had to reconfigure my fstab to get my secondary drive to mount properly, but that's it. Hopefully this helps someone stuck in my position where seemingly no solutions worked!

**Comment by ClarinetK622** [comment]
@1upkd Happy to be of service! This is an annoying problem to run into, for sure.

**Comment by lelaw** [comment]
Any recent success with this instruction - got further for cloning but still can't boot up after mounting cloned disk

> This is an old post, but I tried to follow the solution here and had no luck. For those who are still running into problems, here is an alternative solution.
> 
> I was able to resolve my issues booting a weresync shrunken drive in GCE by **creating the new smaller drive from a public bootable image** (Ubuntu 18.04 LTS: ubuntu-1804-bionic-v20210504). This marks the the drive as UEFI compatible, whereas when I started with a blank drive it would not let me set it as a boot disk on my UEFI instance. It also created a partition 14 on the new drive by default which weresync always failed to copy over from the old one (not sure how important this is). I then mounted the drive onto my VM and cloned my source boot drive to it using weresync with the following command. Notice my source drive has an EFI partition, which also may have been the cause of my problems when following the above solutions.
> 
> sudo weresync -C -L grub2 -E 15 -g 1 /dev/sda /dev/sdc
> 
> I then stopped the server, replaced the large boot drive with the smaller one, and it booted right up. I had to reconfigure my fstab to get my secondary drive to mount properly, but that's it. Hopefully this helps someone stuck in my position where seemingly no solutions worked!

Error I get from the serial console 
```
[2J[01;01H[=3h[2J[01;01H[2J[01;01H[=3h[2J[01;01HBdsDxe: loading Boot0006 "ubuntu" from HD(15,GPT,7861E405-0DDF-46F0-A8D0-EC950C855EE5,0x2800,0x35000)/\EFI\ubuntu\shimx64.efi
BdsDxe: starting Boot0006 "ubuntu" from HD(15,GPT,7861E405-0DDF-46F0-A8D0-EC950C855EE5,0x2800,0x35000)/\EFI\ubuntu\shimx64.efi

UEFI: Attempting to start image.
Description: ubuntu
FilePath: HD(15,GPT,7861E405-0DDF-46F0-A8D0-EC950C855EE5,0x2800,0x35000)/\EFI\ubuntu\shimx64.efi
OptionNumber: 6.

error: no such device: dadca5e3-95e3-45fa-b9e3-0a013e7cdba.

[0m[30m[40m[2J[01;01H[0m[37m[40m[0m[30m[40m[2J[01;01H[0m[37m[40m[02;30HGNU GRUB  version 2.04


   Minimal BASH-like line editing is supported. For the first word, TAB   

   lists possible command completions. Anywhere else TAB lists possible   

   device or file completions.                                            



grub> 
```
