### ISSUE TITLE
After installing via pip, the weresync command is still not available.

### ISSUE THREAD

**Issue by silentwarrior** [DonyorM/weresync#6]
WereSync Version [0.2]:
Name of Distribution (ex. Ubuntu): Ubuntu
Version of Distribution (ex. 16.04): 16.10
Python version (ex. 3.4): 
[Gist](https://gist.github.com) linking to log file (found in /var/log/weresync):
Expected Behavior: 

On typing weresync, see it execute.

Actual Behavior:

zsh: command not found: weresync

Other relevant details:

**Comment by DonyorM** [comment]
Hmmm, did you install with pip as root? (With `sudo pip3 install weresync`)? It's possible you installed weresync to your local folder, which may not be on your PATH.

**Comment by DonyorM** [comment]
No response, assuming suggested response solved the issue.
