### ISSUE TITLE
Arch Linux Feedback

### ISSUE THREAD

**Issue by joelwurtz** [DonyorM/weresync#8]
Hey,

Just to want to give some feedback about Arch Linux, so everything went smoothly, i just have to install some packages (like rsync gptfdisk sgdisk parted).

Since i use systemd boot it give me an error in the end (but related to grub), and in order to complete the switch from my hdd to sdd i just change the PARTUUID number in my boot entries.

Just want to thank you for making this software, it saves me a huge amount of time ❤️ 

PS : Not really an issue, so you can close it if you want.

**Comment by DonyorM** [comment]
I'm glad this helps! Thank you for reporting.

I'm working on changing the boot system over to a plugin based system, and I'll add support for a variety of other bootloaders. Sounds like systemd won't be too hard to support.
